.TH DEADBEEF 1 "20 August 2009" "Version 0.1.1" "deadbeef manual page"
.SH NAME
deadbeef \- ultimate music player for X.
.SH SYNOPSIS
.B deadbeef
[\fIOptions\fR] [\fIFile\fR]
.SH DESCRIPTION
\fIDeadbeef\fP DeaDBeeF (as in 0xDEADBEEF) is an audio player for GNU/Linux
systems with X11.
.SH OPTIONS
.SS "Arguments:"
.TP
File(s)
file(s) to open
.SS "Options:"
.TP
.BI \-h, \-\-help
Show help about options
.TP
.BI \-\-play
Start playback
.TP
.BI \-\-stop
Stop playback
.TP
.BI \-\-pause
Pause playback
.TP
.BI \-\-next
Next song in playlist
.TP
.BI \-\-prev
Previous song in playlist
.TP
.BI \-\-random
Previous song in playlist
.TP
.BI \-\-queue
Append file(s) to existing playlist
.SH "AUTHOR"
DeaDBeeF was written by
.nh
.ad l
Alexey Yakovenko <waker@users.sourceforge.net>
.hy
.br
This manual page was prepared by
.nh
.ad l
Alexey Smirnov <alexey.smirnov@gmx.com>
.hy
for the Debian GNU/Linux system (but may be used by others).
